### ISSUE TITLE
Exporting results without content

### ISSUE THREAD

**Issue by pienisieni** [get-set-fetch/extension#59]
I'd like to just scrape the URLs off a single (static) page, without having to visit each URL.

I figured I could just leave 'selectors' empty and end up with all the URLs I wanted in the results. But when I try to export them, it only includes the URLs that have scraped content in them in the CSV.

Could it be possible to scrape the URLs only?
Thank you.

![GSF_Admin_Area](https://user-images.githubusercontent.com/9020358/103204863-9cf2fb80-493b-11eb-8067-c4ed5b31021c.jpg)

**Comment by a1sabau** [comment]
If it's a single static page just define ExtractUrlsPlugin with maxDepth 0 and empty selectors. This will ensure just the start url will be scraped.

Fortunately ExtractHtmlContentPlugin supports your use case. Just use a selector pair like: 
a[href$=png], href # extract urls as content from png links present in the page

Here's a config hash for such a project (new project > config hash > paste below value):
eLtI4gnapZTBCsIwDEB/pYhHt3kW/APBi+BBpNQt68JmV5qq+PemG5tuIDo9FNKkpU15r/1SaFsReXMfyAQ7QL0KhfeWVkkCJr5hiRYyVHHtdBJmyQbJyzqXlTL6wj2RPN2luZxP4ELaMJ5XkGRBleBoqJUGHxGPPDgQdQUOnLIQMXUe0+iJ5T8KLn9yroWyy+8VejQ6lEc+vsF9TPgA/7TgF4PdK8TNcVsLrnGaxl/Ft1wPsP5k6kSM1aFwkM/X1ujjQoSYf44KTUnCOiDeLtAIX4CwDMNsAsvT2H0AqHL3GA==

Happy scraping :)
