### ISSUE TITLE
How do I support you and this awesome little project?

### ISSUE THREAD

**Issue by thadguidry** [get-set-fetch/extension#73]
Perhaps you can setup the Org with GitHub Sponsors?

**Comment by a1sabau** [comment]
Thank you for the kind words :) Everybody loves to receive positive feedback :)
Staring this project is enough. You've already done that so thank you.

If you want to go the extra mile, review the extension on firefox and/or chrome stores, blog about it.

Like most open source devs, what matters to me most is seeing the project grow. As you said, it's a little project with almost no traffic so I don't think setting up Github Sponsors will have any kind of meaningful impact. If the project takes off, I'll definitely consider it.
